export const SET_EDIT_AGENCY_DATA = "SET_EDIT_AGENCY_DATA";
export const SET_RETAILER_ID = "SET_RETAILER_ID";
export const SET_SALES_CHANNEL_ID = "SET_SALES_CHANNEL_ID";
export const SET_USER_LEAVES_ID = "SET_USER_LEAVES_ID";
